-- MySQL Script generated by MySQL Workbench
-- Fri Oct  2 14:36:28 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Department` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `dept_no` INT NOT NULL,
  `dept_name` VARCHAR(45) NULL,
  PRIMARY KEY (`dept_no`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `employee_no` INT NOT NULL,
  `employee_name` VARCHAR(45) NULL,
  `dept_no` INT NOT NULL,
  PRIMARY KEY (`employee_no`),
  INDEX `fk_Employee_Department_idx` (`dept_no` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Department`
    FOREIGN KEY (`dept_no`)
    REFERENCES `mydb`.`Department` (`dept_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Project` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
  `project_code` INT NOT NULL,
  `project_title` VARCHAR(45) NULL,
  `project_manager` VARCHAR(45) NULL,
  `project_budget` DECIMAL(10) NULL,
  PRIMARY KEY (`project_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Skill` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Skill` (
  `skill_code` INT NOT NULL,
  `skill_type` VARCHAR(45) NULL,
  PRIMARY KEY (`skill_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee_Skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employee_Skill` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employee_Skill` (
  `employee_no` INT NOT NULL,
  `skill_code` INT NOT NULL,
  `Skill_level` DECIMAL(10,2) NULL,
  PRIMARY KEY (`skill_code`, `employee_no`),
  INDEX `fk_Employee_has_Skill_Skill1_idx` (`skill_code` ASC) VISIBLE,
  INDEX `fk_Employee_has_Skill_Employee1_idx` (`employee_no` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_has_Skill_Employee1`
    FOREIGN KEY (`employee_no`)
    REFERENCES `mydb`.`Employee` (`employee_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_has_Skill_Skill1`
    FOREIGN KEY (`skill_code`)
    REFERENCES `mydb`.`Skill` (`skill_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Project_Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Project_Employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Project_Employee` (
  `Project_project_code` INT NOT NULL,
  `Employee_employee_no` INT NOT NULL,
  `Hourly_rate` DECIMAL(10,2) NULL,
  PRIMARY KEY (`Project_project_code`, `Employee_employee_no`),
  INDEX `fk_Project_has_Employee_Employee1_idx` (`Employee_employee_no` ASC) VISIBLE,
  INDEX `fk_Project_has_Employee_Project1_idx` (`Project_project_code` ASC) VISIBLE,
  CONSTRAINT `fk_Project_has_Employee_Project1`
    FOREIGN KEY (`Project_project_code`)
    REFERENCES `mydb`.`Project` (`project_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_has_Employee_Employee1`
    FOREIGN KEY (`Employee_employee_no`)
    REFERENCES `mydb`.`Employee` (`employee_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
